#include <pybind11/pybind11.h>

#include "PCBasis.h"
#include "PCSet.h"

namespace py = pybind11;

PYBIND11_MODULE(_pce, m) {
    py::class_<PCBasis>(m,"PCBasis")
      .def(py::init<const string, const double, const double, const int>())
      .def("Init1dQuadPoints",&PCBasis::Init1dQuadPoints)
      .def("Eval1dBasisAtQuadPoints",&PCBasis::Eval1dBasisAtQuadPoints)
      .def("Eval1dBasisAtCustPoints",&PCBasis::Eval1dBasisAtCustPoints)
      .def("EvalBasis",static_cast<double (PCBasis::*)(const double &, Array1D<double> &) const>(&PCBasis::EvalBasis))
      .def("EvalBasis",static_cast<double (PCBasis::*)(const double &, const int, double *) const>(&PCBasis::EvalBasis))
      .def("Eval1dNormSq_Exact",&PCBasis::Eval1dNormSq_Exact)
      .def("EvalDerivBasis",&PCBasis::EvalDerivBasis)
      .def("Eval1dDerivBasisAtCustPoints",&PCBasis::Eval1dDerivBasisAtCustPoints)
      .def("Eval2ndDerivBasis",&PCBasis::Eval2ndDerivBasis)
      .def("Eval2ndDerivCustPoints",&PCBasis::Eval2ndDerivCustPoints)
      .def("Get1dNormsSq",&PCBasis::Get1dNormsSq)
      .def("Get1dNormsSqExact",&PCBasis::Get1dNormsSqExact)
      .def("GetRandSample",static_cast<void (PCBasis::*)(Array1D<double>&)>(&PCBasis::GetRandSample))
      .def("GetRandSample",static_cast<void (PCBasis::*)(double*, const int&)>(&PCBasis::GetRandSample))
      .def("GetSeed",&PCBasis::GetSeed)
      .def("SeedRandNumGen",&PCBasis::SeedRandNumGen)
      .def("GetQuadRule",&PCBasis::GetQuadRule)
      .def("GetQuadPoints",&PCBasis::GetQuadPoints)
      .def("GetQuadWeights",&PCBasis::GetQuadWeights)
      .def("GetQuadIndices",&PCBasis::GetQuadIndices)
      .def("GetBasisAtQuadPoints",&PCBasis::GetBasisAtQuadPoints)
      .def("GetPCType",&PCBasis::GetPCType)
      .def("GetAlpha",&PCBasis::GetAlpha)
      .def("GetBeta",&PCBasis::GetBeta)
      ;

      py::class_<PCSet>(m,"PCSet")
        .def(py::init<const string, const int, const int, const string, const double, const double>())
        .def(py::init<const string, const int, const int, const string, const string, const double, const double>())
        .def(py::init<const string, const Array1D<int>&, const int, const string, const double, const double>())
        .def(py::init<const string, const Array2D<int>&, const string, const double, const double>())
        .def("dPhi_alpha",&PCSet::dPhi_alpha)
        .def("dPhi",static_cast<void (PCSet::*)(Array1D<double>&, Array2D<int>&, Array1D<double>&, Array1D<double>&)>(&PCSet::dPhi))
        .def("dPhi",static_cast<void (PCSet::*)(Array2D<double>&, Array2D<int>&, Array1D<double>&, Array1D<double>&)>(&PCSet::dPhi))
        .def("ddPhi_alpha",&PCSet::ddPhi_alpha)
        .def("ddPhi",&PCSet::ddPhi)
        .def("SetQd1d",&PCSet::SetQd1d)
        .def("SetQuadRule",static_cast<void (PCSet::*)(const string,const string,int)>(&PCSet::SetQuadRule))
        .def("SetQuadRule",static_cast<void (PCSet::*)(Quad&)>(&PCSet::SetQuadRule))
        .def("PrintMultiIndex",&PCSet::PrintMultiIndex)
        .def("PrintMultiIndexNormSquared",&PCSet::PrintMultiIndexNormSquared)
        .def("GetPCType",&PCSet::GetPCType)
        .def("GetAlpha",&PCSet::GetAlpha)
        .def("GetBeta",&PCSet::GetBeta)
        .def("GetMultiIndex",static_cast<void (PCSet::*)(Array2D<int> &) const>(&PCSet::dPhi))
        .def("GetMultiIndex",static_cast<void (PCSet::*)(int *) const>(&PCSet::dPhi))
        .def("GetNormSq",&PCSet::GetNormSq)
        .def("GetNumberPCTerms",&PCSet::GetNumberPCTerms)
        .def("GetNDim",&PCSet::GetNDim)
        .def("GetOrder",&PCSet::GetOrder)
        .def("GetNQuadPoints",&PCSet::GetNQuadPoints)
        .def("GetQuadPoints",static_cast<void (PCSet::*)(Array2D<double>&) const>(&PCSet::GetQuadPoints))
        .def("GetQuadPoints",static_cast<void (PCSet::*)(double *) const>(&PCSet::GetQuadPoints))
        .def("GetQuadPointsWeights",&PCSet::GetQuadPointsWeights)
        .def("GetQuadWeights",static_cast<void (PCSet::*)(Array1D<double>&) const>(&PCSet::GetQuadPoints))
        .def("GetQuadWeights",static_cast<void (PCSet::*)(double *) const>(&PCSet::GetQuadWeights))
        .def("GetPsi",static_cast<void (PCSet::*)(Array2D<double>&) const>(&PCSet::GetPsi))
        .def("GetPsi",static_cast<void (PCSet::*)(double *) const>(&PCSet::GetPsi))
        .def("GetPsiSq",static_cast<void (PCSet::*)(Array1D<double>&) const>(&PCSet::GetPsiSq))
        .def("GetPsiSq",static_cast<void (PCSet::*)(double *) const>(&PCSet::GetPsiSq))
        .def("GetTaylorTolerance",&PCSet::GetTaylorTolerance)
        .def("SetTaylorTolerance",&PCSet::SetTaylorTolerance)
        .def("GetTaylorTermsMax",&PCSet::GetTaylorTermsMax)
        .def("SetTaylorTermsMax",&PCSet::SetTaylorTermsMax)
        .def("SetLogCompMethod",&PCSet::SetLogCompMethod)
        .def("GetGMRESDivTolerance",static_cast<double (PCSet::*)() const>(&PCSet::GetGMRESDivTolerance))
        .def("GetGMRESDivTolerance",static_cast<void (PCSet::*)(const double&)>(&PCSet::GetGMRESDivTolerance))
        
        ;
}
