#include <pybind11/pybind11.h>
#include <>

PYBIND11_MODULE(uqtkarray, m) {
    py::class_<Array1D<int>>(m, "Array1D<int>")
      .def(py::init<>())
      .def(py::init<const int&>())
      .def(py::init<const int&,const int&>())
      .def("Assign", &Array1D::operator=)
      .def(py::init<const Array1D &>())
      .def("Clear",&Array1D::Clear)
      .def("XSize",&Array1D::XSize)
      .def("Length",&Array1D::Length)
      .def("Resize",static_cast<void (Array1D::*)(const int&)>(&Array1D::Resize))
      .def("Resize",static_cast<void (Array1D::*)(const int&,const int&)>(&Array1D::Resize))
      .def("SetValue",&Array1D::SetValue)
      .def("PushBack",&Array1D::PushBack)
      .def("GetArrayPointer",&Array1D::GetArrayPointer)
      .def("GetConstArrayPointer",&Array1D::GetConstArrayPointer)
      .def("element",&Array1D::operator())
      .def("insert",static_cast<void (Array1D::*)(Array1D<int>&,int)>(&Array1D::insert))
      .def("insert",static_cast<void (Array1D::*)(const int&,int)>(&Array1D::insert))
      .def("erase",&Array1D::erase)
      .def("DumpBinary",static_cast<void (Array1D::*)(FILE*)>(&Array1D::DumpBinary)))
      .def("DumpBinary",static_cast<void (Array1D::*)(char*)>(&Array1D::DumpBinary)))
      .def("ReadBinary",static_cast<void (Array1D::*)(FILE*)>(&Array1D::ReadBinary)))
      .def("ReadBinary",static_cast<void (Array1D::*)(char*)>(&Array1D::ReadBinary)))
      .def("pyElement",&Array1D::operator[])
      .def("ReadBinary4py",&Array1D::ReadBinary4py)
      .def("DumpBinary4py",&Array1D::DumpBinary4py)
      .def("setArray",&Array1D::setArray)
      .def("setnpintArray",&Array1D::setnpintArray)
      .def("getnpintArray",&Array1D::getnpintArray)
      .def("flatten",&Array1D::flatten)
      .def("type",&Array1D::type)

      py::class_<Array1D<double>>(m, "Array1D<int>")
        .def(py::init<>())
        .def(py::init<const int&>())
        .def(py::init<const int&,const int&>())
        .def("Assign", &Array1D::operator=)
        .def(py::init<const Array1D &>())
        .def("Clear",&Array1D::Clear)
        .def("XSize",&Array1D::XSize)
        .def("Length",&Array1D::Length)
        .def("Resize",static_cast<void (Array1D::*)(const int&)>(&Array1D::Resize))
        .def("Resize",static_cast<void (Array1D::*)(const int&,const double&)>(&Array1D::Resize))
        .def("SetValue",&Array1D::SetValue)
        .def("PushBack",&Array1D::PushBack)
        .def("GetArrayPointer",&Array1D::GetArrayPointer)
        .def("GetConstArrayPointer",&Array1D::GetConstArrayPointer)
        .def("element",&Array1D::operator())
        .def("insert",static_cast<void (Array1D::*)(Array1D<double>&,int)>(&Array1D::insert))
        .def("insert",static_cast<void (Array1D::*)(const double&,int)>(&Array1D::insert))
        .def("erase",&Array1D::erase)
        .def("DumpBinary",static_cast<void (Array1D::*)(FILE*)>(&Array1D::DumpBinary)))
        .def("DumpBinary",static_cast<void (Array1D::*)(char*)>(&Array1D::DumpBinary)))
        .def("ReadBinary",static_cast<void (Array1D::*)(FILE*)>(&Array1D::ReadBinary)))
        .def("ReadBinary",static_cast<void (Array1D::*)(char*)>(&Array1D::ReadBinary)))
        .def("pyElement",&Array1D::operator[])
        .def("ReadBinary4py",&Array1D::ReadBinary4py)
        .def("DumpBinary4py",&Array1D::DumpBinary4py)
        .def("setArray",&Array1D::setArray)
        .def("setnpdblArray",&Array1D::setnpintArray)
        .def("getnpdblArray",&Array1D::getnpintArray)
        .def("flatten",&Array1D::flatten)
        .def("type",&Array1D::type)

      
}
